# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # build server specs with requirements.
    container:
      image: docker:20.10.16
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile the code
        run: |
          echo "Compiling the code..."
          echo "Compile complete."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploying the application
        run: |
          echo "Starting deployment..."
          sleep 5
          echo "Deployment complete."
